baseURL = "https://stevemcghee.dev/"
languageCode = "en-us"
title = "Steve McGhee"
theme = "PaperMod"

[params]
  env = "production"
  description = "Personal website of Steve McGhee - Software Engineer, Speaker, and Podcaster"
  author = "Steve McGhee"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = false
  disableSpecial1stPost = false
  disableScrollToTop = false
  disableThemeToggle = true
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 20
  [[menu.main]]
    identifier = "podcasts"
    name = "Podcasts"
    url = "/podcasts/"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true 