baseURL = "https://stevemcghee.dev/"
languageCode = "en-us"
title = "Steve McGhee"
theme = "PaperMod"

[params]
  env = "production"
  description = "Personal website of Steve McGhee - Software Engineer, Speaker, and Podcaster"
  keywords = ["Steve McGhee", "Software Engineering", "Videos", "Podcasts", "Blog"]
  author = "Steve McGhee"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

  # Custom social icons
  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/stevemcghee"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/stevemcghee"

  # Profile mode
  [params.profileMode]
  enabled = true
  title = "Steve McGhee"
  subtitle = "Software Engineer, Speaker, and Podcaster"
  imageUrl = "/images/bw-portrait.jpg"
  imageTitle = "Steve McGhee"
  imageWidth = 250
  imageHeight = 250

  # Home Info Mode
  [params.homeInfoParams]
  Title = "Steve McGhee"
  Content = "Software Engineer, Speaker, and Podcaster"

  # Theme appearance
  [params.assets]
  disableHLJS = true
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 20
  [[menu.main]]
    identifier = "podcasts"
    name = "Podcasts"
    url = "/podcasts/"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40

# Syntax highlighting
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
    style = "dracula"
