baseURL = "https://stevemcghee.dev/"
languageCode = "en-us"
title = "Steve McGhee"
theme = "PaperMod"

[params]
  env = "production"
  description = "Personal website of Steve McGhee - Software Engineer, Speaker, and Podcaster"
  keywords = ["Steve McGhee", "Software Engineering", "Videos", "Podcasts", "Blog"]
  author = "Steve McGhee"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "videos"
    name = "Videos"
    url = "/videos/"
    weight = 20
  [[menu.main]]
    identifier = "podcasts"
    name = "Podcasts"
    url = "/podcasts/"
    weight = 30
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40

[params.homeInfoParams]
  Title = "Steve McGhee"
  Content = "Software Engineer, Speaker, and Podcaster"
